/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#faf9f8",
        "surface-dim": "#dadad9",
        "surface-bright": "#faf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f2",
        "surface-container": "#eeeeed",
        "surface-container-high": "#e9e8e7",
        "surface-container-highest": "#e3e2e1",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#40484b",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f0f0",
        outline: "#70787c",
        "outline-variant": "#c0c8cb",
        "surface-tint": "#306576",
        primary: "#003644",
        "on-primary": "#ffffff",
        "primary-container": "#134e5e",
        "on-primary-container": "#8abed1",
        "inverse-primary": "#9acee1",
        secondary: "#904d00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe932c",
        "on-secondary-container": "#663500",
        tertiary: "#582000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#77340e",
        "on-tertiary-container": "#fe9f71",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#b6ebfe",
        "primary-fixed-dim": "#9acee1",
        "on-primary-fixed": "#001f28",
        "on-primary-fixed-variant": "#124d5d",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#6e3900",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#ffb693",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#76330d",
        background: "#faf9f8",
        "on-background": "#1a1c1c",
        "surface-variant": "#e3e2e1",
        sand: "#F5F2ED", // Added specifically for the input backgrounds mentioned in the spec
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "13px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
      },
      spacing: {
        base: "8px",
        "container-mobile": "20px",
        "container-desktop": "40px",
        gutter: "24px",
        "section-gap": "64px",
      },
    },
  },
};
